-- Weekly AI Insights Table
-- Charlotte generates weekly reports with pattern analysis and recommendations

CREATE TABLE IF NOT EXISTS weekly_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,

  -- Summary Stats
  total_sessions INT DEFAULT 0,
  unique_strains INT DEFAULT 0,
  cognitive_average DECIMAL(5,2),
  cognitive_change_percent DECIMAL(5,2), -- vs previous week
  cognitive_trend TEXT, -- 'improving', 'stable', 'declining'

  -- Patterns Detected
  patterns JSONB DEFAULT '[]'::jsonb,
  -- Example: [
  --   {
  --     "type": "consumption_frequency",
  --     "severity": "high",
  --     "description": "Daily use detected for 6+ days",
  --     "recommendation": "Consider T-break"
  --   }
  -- ]

  -- Insights
  insights JSONB DEFAULT '[]'::jsonb,
  -- Example: [
  --   {
  --     "type": "correlation",
  --     "title": "Evening consumption = better focus",
  --     "description": "Your cognitive scores are 15% higher when you consume after 6pm",
  --     "confidence": 0.85
  --   }
  -- ]

  -- Achievements
  achievements JSONB DEFAULT '[]'::jsonb,
  -- Example: [
  --   {
  --     "type": "streak",
  --     "title": "5-day check-in streak!",
  --     "icon": "🔥"
  --   }
  -- ]

  -- Recommendations
  recommendations JSONB DEFAULT '[]'::jsonb,
  -- Example: [
  --   {
  --     "type": "harm_reduction",
  --     "priority": "high",
  --     "message": "Consider 2-week T-break to reset tolerance"
  --   }
  -- ]

  -- Comparison with previous week
  comparison JSONB DEFAULT '{}'::jsonb,
  -- Example: {
  --   "sessions": {"current": 6, "previous": 4, "change": "+50%"},
  --   "cognitive": {"current": 82, "previous": 85, "change": "-3.5%"}
  -- }

  -- Goals Progress
  goals_progress JSONB DEFAULT '[]'::jsonb,
  -- Example: [
  --   {
  --     "goal": "Track all sessions",
  --     "progress": 0.85,
  --     "status": "on_track"
  --   }
  -- ]

  -- AI-generated summary
  summary TEXT,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  viewed_at TIMESTAMPTZ,
  is_viewed BOOLEAN DEFAULT FALSE,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, week_start)
);

-- Indexes
CREATE INDEX idx_weekly_insights_user_id ON weekly_insights(user_id);
CREATE INDEX idx_weekly_insights_week_start ON weekly_insights(week_start);
CREATE INDEX idx_weekly_insights_viewed ON weekly_insights(user_id, is_viewed);

-- RLS Policies
ALTER TABLE weekly_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own weekly insights"
  ON weekly_insights FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own weekly insights"
  ON weekly_insights FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own weekly insights"
  ON weekly_insights FOR UPDATE
  USING (auth.uid() = user_id);

-- Function to auto-generate weekly insights (scheduled via pg_cron or edge function)
CREATE OR REPLACE FUNCTION generate_weekly_insights()
RETURNS void AS $$
DECLARE
  target_user RECORD;
  week_start_date DATE;
  week_end_date DATE;
BEGIN
  -- Get previous week (Sunday to Saturday)
  week_end_date := CURRENT_DATE - EXTRACT(DOW FROM CURRENT_DATE)::INT;
  week_start_date := week_end_date - 6;

  -- For each active user (had activity in last week)
  FOR target_user IN
    SELECT DISTINCT user_id
    FROM consumption_logs
    WHERE timestamp >= week_start_date
      AND timestamp < week_end_date + 1
  LOOP
    -- Insert placeholder - actual insights generated by app/edge function
    INSERT INTO weekly_insights (
      user_id,
      week_start,
      week_end,
      summary
    )
    VALUES (
      target_user.user_id,
      week_start_date,
      week_end_date,
      'Weekly insights are being generated...'
    )
    ON CONFLICT (user_id, week_start) DO NOTHING;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_weekly_insights_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER weekly_insights_updated_at
  BEFORE UPDATE ON weekly_insights
  FOR EACH ROW
  EXECUTE FUNCTION update_weekly_insights_updated_at();

COMMENT ON TABLE weekly_insights IS 'Charlotte AI weekly report - pattern analysis, insights, and recommendations';
